# Generated by Django 5.1.4 on 2024-12-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_news_height"),
    ]

    operations = [
        migrations.CreateModel(
            name="Songs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("youtube_url", models.CharField(max_length=1000)),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="songs_videos/"),
                ),
            ],
            options={
                "verbose_name": "Songs",
                "verbose_name_plural": "Songs",
            },
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
