# Generated by Django 5.1.4 on 2024-12-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_songs_alter_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='video_file',
        ),
        migrations.AddField(
            model_name='songs',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
    ]
