# Generated by Django 5.1.4 on 2025-01-01 16:04

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president_name', models.CharField(max_length=100)),
                ('president_image', versatileimagefield.fields.VersatileImageField(upload_to='president/')),
                ('vice_president_name', models.CharField(max_length=100)),
                ('vice_president_image', versatileimagefield.fields.VersatileImageField(upload_to='vice_president/')),
                ('secretary_name', models.CharField(max_length=100)),
                ('secretary_image', versatileimagefield.fields.VersatileImageField(upload_to='secretary/')),
                ('vice_secretary_name_1', models.CharField(max_length=100)),
                ('vice_secretary_image_1', versatileimagefield.fields.VersatileImageField(upload_to='vice_secretary/')),
                ('vice_secretary_name_2', models.CharField(max_length=100)),
                ('vice_secretary_image_2', versatileimagefield.fields.VersatileImageField(upload_to='vice_secretary/')),
                ('vice_secretary_name_3', models.CharField(max_length=100)),
                ('vice_secretary_image_3', versatileimagefield.fields.VersatileImageField(upload_to='vice_secretary/')),
                ('treasurer_name', models.CharField(max_length=100)),
                ('treasurer_image', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Our Team',
                'verbose_name_plural': 'Our Team',
            },
        ),
    ]
