# Generated by Django 5.1.4 on 2025-01-01 16:07

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='vice_secretary_image_1',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='vice_secretary/'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='vice_secretary_image_2',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='vice_secretary/'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='vice_secretary_image_3',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='vice_secretary/'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='vice_secretary_name_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='vice_secretary_name_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='vice_secretary_name_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
