# Generated by Django 5.1.4 on 2024-12-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blooddonor',
            options={'verbose_name': 'Blood Donor', 'verbose_name_plural': 'Blood Donors'},
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
